packages:
  - packages/*
  - plugin
  - fake
  - others/*
  - tests

catalog:
  yaml: ^2.8.1

patchedDependencies:
  '@vue-mini/core': patches/@vue-mini__core.patch
  ava: patches/ava.patch

shamefullyHoist: true
