packages:
  - packages/*
  - plugin
  - fake
  - others/*
  - tests

catalog:
  '@padcom/vue-ast-serializer': ^0.0.1
  '@vue/compiler-sfc': ~3.5.21
  '@vue/compiler-core': ~3.5.21
  '@vue-mini/core': ^1.2.4
  '@vue-mini/pinia': ^0.1.2
  vue: ~3.5.21
  yaml: ^2.8.1

patchedDependencies:
  '@vue-mini/core': patches/@vue-mini__core.patch
  ava: patches/ava.patch

shamefullyHoist: true
