packages:
  - packages/*
  - plugin
  - fake
  - others
  - tests

catalog:
  yaml: ^2.8.1

patchedDependencies:
  ava: patches/ava.patch
  '@vue-mini/core': patches/@vue-mini__core.patch

shamefullyHoist: true
