packages:
  - packages/*
  - fake
  - others/*
  - tests

catalog:
  '@padcom/vue-ast-serializer': ^0.0.1
  '@vue-mini/core': ^1.2.8
  '@vue-mini/pinia': ^1.0.0
  '@vue/compiler-core': ^3.5.25
  '@vue/compiler-sfc': ^3.5.25
  vue: ^3.5.25
  vue-router: ^4.6.3
  yaml: ^2.8.2
  ava: ^6.4.1
  prettier: ^3.7.4

patchedDependencies:
  '@vue-mini/core': patches/@vue-mini__core.patch
  ava: patches/ava.patch

shamefullyHoist: true

overrides:
  '@nice-move/tsconfig': ^0.4.0
